language: java

git:
  depth: 5

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2


branches:
  only:
    - master
install: "mvn clean --settings settings.xml"
script: "mvn install --settings settings.xml"
